export const INCREMENT_SPELL_SLOT = 'INCREMENT_SPELL_SLOT';
export const DECREMENT_SPELL_SLOT = 'DECREMENT_SPELL_SLOT';
export const REGAIN_SPELL_SLOT = 'REGAIN_SPELL_SLOT';
export const USE_SPELL_SLOT = 'USE_SPELL_SLOT';